name: CI

on: [push, pull_request]

jobs:
  code-style-checker:
    name: Code Style checker
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP
        run: sudo phpdismod xdebug

      - uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: composer install
        run: composer install --prefer-dist --no-interaction --no-suggest --no-progress

      - name: Run php-cs
        run: composer check-style
