name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  schedule:
  - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      COMPOSER_NO_INTERACTION: 1

    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
        php: [8.1, 8.0, 7.4, 7.3]
        laravel: [8.*, 9.*]
        dependency-version: [prefer-lowest, prefer-stable]
        exclude:
          - php: 8.0
            dependency-version: prefer-lowest
          - php: 7.4
            laravel: 9.*
          - php: 7.3
            laravel: 9.*
          - os: windows-2019
            php: 7.4
          - os: windows-2019
            php: 7.3
    steps:
    - name: Set git to use LF
      if: ${{ matrix.os == 'windows-2019' }}
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none
        extensions: pdo_sqlite, fileinfo

    - name: Install dependencies
      run: |
        composer remove vimeo/psalm --no-update --dev
        composer remove friendsofphp/php-cs-fixer --no-update --dev
        composer require "laravel/framework:${{ matrix.laravel }}" --no-update --no-progress
        composer update --prefer-dist --no-progress

    - name: Execute Unit Tests
      run: composer test-ci
